DROP TABLE IF EXISTS player, play, game, team, roster CASCADE;

CREATE TABLE player(
	player_id serial,
	status VARCHAR(3),
	display_name VARCHAR(50),
	first_name VARCHAR(30),
	last_name VARCHAR(30),
	esb_id VARCHAR(9),
	gsis_id VARCHAR(10) UNIQUE,
	suffix VARCHAR(8),
	birth_date date,
	college_name VARCHAR(40),
	position_group VARCHAR(5),
	position VARCHAR(5),
	jersey_number int,
	height VARCHAR(7),
	weight int,
	team_abbr VARCHAR(5),
	team_seq VARCHAR(20),
	current_team_id VARCHAR(5),
	football_name VARCHAR(15),
	entry_year int,
	rookie_year int,
	draft_club VARCHAR(5),
	college_conference VARCHAR(100),
	status_description_abbr VARCHAR(5),
	status_short_description VARCHAR(20),
	gsis_it_id int,
	short_name VARCHAR(20),
	smart_id VARCHAR(40),
	headshot VARCHAR(100),
	draft_number int,
	uniform_number VARCHAR(5),
	draft_round int,
	season int,
	CONSTRAINT PK_player PRIMARY KEY (player_id)
);

CREATE TABLE team (
	team_id serial,
	name VARCHAR(100),
	abbr VARCHAR(4) UNIQUE,
	conference VARCHAR(3),
	division VARCHAR(5),
	CONSTRAINT PK_team PRIMARY KEY (team_id)
);

CREATE TABLE game (
    game_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    home_team character varying(5) COLLATE pg_catalog."default",
    away_team character varying(5) COLLATE pg_catalog."default",
    season integer,
    season_type character varying(4) COLLATE pg_catalog."default",
    week integer,
    game_date date,
    spread_line numeric,
    total_line numeric,
    roof character varying(25) COLLATE pg_catalog."default",
    home_coach character varying(50) COLLATE pg_catalog."default",
    away_coach character varying(50) COLLATE pg_catalog."default",
    temp integer,
    wind integer,
    CONSTRAINT pk_game PRIMARY KEY (game_id),
    CONSTRAINT fk_game_away_team FOREIGN KEY (away_team) REFERENCES public.team (abbr),
    CONSTRAINT fk_game_home_team FOREIGN KEY (home_team) REFERENCES public.team (abbr)
);

CREATE TABLE roster (
	roster_id serial,
	season int,
	week int,
	team VARCHAR(5),
	position VARCHAR(10),
	depth_chart_position int,
	jersey_number int,
	status VARCHAR(15),
	gsis_id VARCHAR(10),
	ngs_position VARCHAR(25),
	status_description_abbr VARCHAR(25),
	CONSTRAINT PK_roster PRIMARY KEY (roster_id),
	CONSTRAINT FK_roster_team FOREIGN KEY (team) REFERENCES team(abbr),
	CONSTRAINT FK_roster_gsis_id FOREIGN KEY (gsis_id) REFERENCES player(gsis_id)
);



--REFERENCE: https://nflreadr.nflverse.com/articles/dictionary_pbp.html

CREATE TABLE play
(
    play_id integer NOT NULL,
    game_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    posteam character varying(5) COLLATE pg_catalog."default",
    defteam character varying(5) COLLATE pg_catalog."default",
    yardline_100 integer,
    game_seconds_remaining integer,
    drive integer,
    qtr integer,
    down integer,
    ydstogo integer,
    ydsnet integer,
    play_desc text COLLATE pg_catalog."default",
    play_type character varying(15) COLLATE pg_catalog."default",
    yards_gained integer,
    pass_location character varying(10) COLLATE pg_catalog."default",
    run_location character varying(10) COLLATE pg_catalog."default",
    run_gap character varying(10) COLLATE pg_catalog."default",
    timeout_team character varying(5) COLLATE pg_catalog."default",
    posteam_timeouts_remaining integer,
    defteam_timeouts_remaining integer,
    posteam_score integer,
    defteam_score integer,
    penalty_type text COLLATE pg_catalog."default",
    series_result text COLLATE pg_catalog."default",
    play_clock integer,
    passer_jersey_number integer,
    play_type_nfl character varying(25) COLLATE pg_catalog."default",
    penalty_team character varying(5) COLLATE pg_catalog."default",
    td_player_id character varying(10) COLLATE pg_catalog."default",
    passer_player_id character varying(10) COLLATE pg_catalog."default",
    air_yards integer,
    yards_after_catch integer,
    passing_yards integer,
    receiver_player_id character varying(10) COLLATE pg_catalog."default",
    receiving_yards integer,
    rusher_player_id character varying(10) COLLATE pg_catalog."default",
    rushing_yards integer,
    interception_player_id character varying(10) COLLATE pg_catalog."default",
    sack_player_id character varying(10) COLLATE pg_catalog."default",
    punt_returner_player_id character varying(10) COLLATE pg_catalog."default",
    kickoff_returner_player_id character varying(10) COLLATE pg_catalog."default",
    return_yards integer,
    penalty_yards integer,
    punter_player_id character varying(10) COLLATE pg_catalog."default",
    kicker_player_id character varying(10) COLLATE pg_catalog."default",
    kick_distance integer,
    opp_fg_prob numeric,
    opp_safety_prob numeric,
    opp_td_prob numeric,
    fg_prob numeric,
    safety_prob numeric,
    td_prob numeric,
    extra_point_prob numeric,
    two_point_conversion_prob numeric,
    ep numeric,
    epa numeric,
    air_epa numeric,
    yac_epa numeric,
    qb_epa numeric,
    wp numeric,
    def_wp numeric,
    wpa numeric,
    vegas_wpa numeric,
    vegas_wp numeric,
    air_wpa numeric,
    yac_wpa numeric,
    timeout boolean,
    shotgun boolean,
    no_huddle boolean,
    qb_dropback boolean,
    qb_kneel boolean,
    qb_spike boolean,
    qb_scramble boolean,
    punt_blocked boolean,
    touchback boolean,
    interception boolean,
    fumble boolean,
    fumble_forced boolean,
    fumble_not_forced boolean,
    fumble_out_of_bounds boolean,
    fumble_lost boolean,
    solo_tackle boolean,
    safety boolean,
    penalty boolean,
    qb_hit boolean,
    rush_attempt boolean,
    pass_attempt boolean,
    sack boolean,
    touchdown boolean,
    complete_pass boolean,
    start_time timestamp without time zone,
    time_of_day timestamp without time zone,
	
    CONSTRAINT pk_play PRIMARY KEY (play_id, game_id),
    CONSTRAINT fk_play_defteam FOREIGN KEY (defteam) REFERENCES team (abbr),
    CONSTRAINT fk_play_game_id FOREIGN KEY (game_id) REFERENCES public.game (game_id),
    CONSTRAINT fk_play_interception_player_id FOREIGN KEY (interception_player_id) REFERENCES public.player (gsis_id),
    CONSTRAINT fk_play_kicker_player_id FOREIGN KEY (kicker_player_id) REFERENCES public.player (gsis_id),
    CONSTRAINT fk_play_kickoff_returner_player_id FOREIGN KEY (kickoff_returner_player_id) REFERENCES public.player (gsis_id),
    CONSTRAINT fk_play_passer_player_id FOREIGN KEY (passer_player_id) REFERENCES public.player (gsis_id),
    CONSTRAINT fk_play_penalty_team FOREIGN KEY (penalty_team) REFERENCES public.team (abbr),
    CONSTRAINT fk_play_posteam FOREIGN KEY (posteam) REFERENCES public.team (abbr),
    CONSTRAINT fk_play_punt_returner_player_id FOREIGN KEY (punt_returner_player_id) REFERENCES public.player (gsis_id),
    CONSTRAINT fk_play_punter_player_id FOREIGN KEY (punter_player_id) REFERENCES public.player (gsis_id),
    CONSTRAINT fk_play_receiver_player_id FOREIGN KEY (receiver_player_id) REFERENCES public.player (gsis_id),
    CONSTRAINT fk_play_rusher_player_id FOREIGN KEY (rusher_player_id) REFERENCES public.player (gsis_id),
    CONSTRAINT fk_play_sack_player_id FOREIGN KEY (sack_player_id) REFERENCES public.player (gsis_id),
    CONSTRAINT fk_play_td_player_id FOREIGN KEY (td_player_id)  REFERENCES public.player (gsis_id),
    CONSTRAINT fk_play_timeout_team FOREIGN KEY (timeout_team) REFERENCES public.team (abbr)
);


