DROP TABLE IF EXISTS player CASCADE;

CREATE TABLE player(
	player_id serial,
	status VARCHAR(3),
	display_name VARCHAR(50),
	first_name VARCHAR(30),
	last_name VARCHAR(30),
	esb_id VARCHAR(9),
	gsis_id VARCHAR(10),
	suffix VARCHAR(8),
	birth_date date,
	college_name VARCHAR(40),
	position_group VARCHAR(5),
	position VARCHAR(5),
	jersey_number int,
	height VARCHAR(7),
	weight int,
	team_abbr VARCHAR(5),
	team_seq VARCHAR(20),
	current_team_id VARCHAR(5),
	football_name VARCHAR(15),
	entry_year int,
	rookie_year int,
	draft_club VARCHAR(5),
	college_conference VARCHAR(100),
	status_description_abbr VARCHAR(5),
	status_short_description VARCHAR(20),
	gsis_it_id int,
	short_name VARCHAR(20),
	smart_id VARCHAR(40),
	headshot VARCHAR(100),
	draft_number int,
	uniform_number VARCHAR(5),
	draft_round int,
	season int,
	CONSTRAINT PK_player PRIMARY KEY (player_id)
);
